apiVersion: apps/v1
kind: Deployment
metadata:
  name: chitchat
spec:
  selector:
    matchLabels:
      app: chitchat
  replicas: 2
  template:
    metadata:
      name: chitchat
      labels:
        app: chitchat
    spec:
      containers:
      - image: "$(dockerhub):latest"
        name: nodejs
        env:
          - name: dockerhub
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: dockerhuburl

---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.0.35
  selector:
    app: chitchat
  ports:
  - port: 8080
    targetPort: 4141
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap
  namespace: default
data:
  # Configuration values can be set as key-value properties
  dockerhuburl: 2871/chitchat

