apiVersion: apps/v1
kind: Deployment
metadata:
  name: chitchat
spec:
  selector:
    matchLabels:
      app: chitchat
  replicas: 2
  template:
    metadata:
      name: chitchat
      labels:
        app: chitchat
    spec:
      containers:
      - image: 2871/chitchat:latest
        name: nodejs

---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.0.35
  selector:
    app: chitchat
  ports:
  - port: 8080
    targetPort: 4141

